version: "3.1"
services:

  httpd:
    build: ./docker/httpd
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  php:
    build: ./docker/php
    expose:
      - 9000
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  redis:
    build: ./docker/redis
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
